import { useEffect, useMemo, useState } from 'react'
import { getApplications, updateApplicationStage } from '../services/api'
import ActionModal from '../components/ActionModal'
import { downloadCsv } from '../utils/exportCsv'

const stageIcons={Applied:'bi-send',Screening:'bi-search',Shortlisted:'bi-person-check',Interview:'bi-calendar2-check',Offer:'bi-file-earmark-check',Hired:'bi-person-badge'}
const stageOrder=['Applied','Screening','Shortlisted','Interview','Offer','Hired']

export default function Applications(){
 const [apps,setApps]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [stageFilter,setStageFilter]=useState('All');const [range,setRange]=useState('All time');const [selected,setSelected]=useState(null)
 async function load(){setLoading(true);setError('');try{const d=await getApplications();setApps(d.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>{const now=Date.now();const days=range==='30 days'?30:range==='7 days'?7:null;return apps.filter(a=>(stageFilter==='All'||a.stage===stageFilter)&&(!days||now-new Date(a.applied).getTime()<=days*86400000))},[apps,stageFilter,range])
 const stages=useMemo(()=>stageOrder.map(stage=>[stage,apps.filter(a=>a.stage===stage).length,stageIcons[stage]]),[apps])
 async function setStage(stage){if(!selected)return;try{await updateApplicationStage(selected.id,stage);setSelected({...selected,stage});await load()}catch(e){setError(e.message)}}
 return <><div className="page-title-row"><div><div className="eyebrow">HIRING PIPELINE</div><h1>Applications</h1><p>Track candidate movement from application to offer.</p></div><button className="btn btn-primary-custom" onClick={()=>document.getElementById('application-filters')?.scrollIntoView({behavior:'smooth'})}><i className="bi bi-funnel me-2"/>Pipeline filters</button></div>
 {error&&<div className="alert alert-warning">{error}</div>}
 <div className="pipeline-row">{stages.map((s,i)=><button className="pipeline-stage" key={s[0]} onClick={()=>setStageFilter(s[0])}><div className="pipeline-icon"><i className={`bi ${s[2]}`}/></div><span>{s[0]}</span><strong>{s[1].toLocaleString()}</strong>{i<stages.length-1&&<i className="bi bi-chevron-right pipeline-arrow"/>}</button>)}</div>
 <div id="application-filters" className="panel mt-4"><div className="row g-3 align-items-end"><div className="col-md-6"><label className="form-label">Stage</label><select className="form-select" value={stageFilter} onChange={e=>setStageFilter(e.target.value)}><option>All</option>{stageOrder.map(s=><option key={s}>{s}</option>)}</select></div><div className="col-md-6"><label className="form-label">Date range</label><select className="form-select" value={range} onChange={e=>setRange(e.target.value)}><option>All time</option><option>30 days</option><option>7 days</option></select></div></div></div>
 <div className="panel mt-4"><div className="panel-head"><div><h3>Recent applications</h3><p>{loading?'Loading live applications...':`${filtered.length} applications shown from PostgreSQL.`}</p></div><div className="d-flex gap-2"><button className="btn btn-outline-soft" onClick={()=>setRange(range==='All time'?'30 days':range==='30 days'?'7 days':'All time')}>{range}</button><button className="btn btn-outline-soft" onClick={()=>downloadCsv('hiresense-applications.csv',filtered)}><i className="bi bi-download"/></button></div></div><div className="table-responsive"><table className="table align-middle candidate-table"><thead><tr><th>Candidate</th><th>Position</th><th>Match</th><th>Stage</th><th>Applied</th><th></th></tr></thead><tbody>{!loading&&filtered.map(a=><tr key={a.id}><td><div className="candidate-name"><div className="avatar-sm">{a.candidate.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{a.candidate}</strong><small>APP-{String(a.id).padStart(4,'0')}</small></div></div></td><td>{a.role}</td><td><span className="match-pill">{a.match}%</span></td><td><span className={`status ${a.stage.toLowerCase()}`}>{a.stage}</span></td><td>{a.applied}</td><td><button className="icon-btn" onClick={()=>setSelected(a)}><i className="bi bi-three-dots"/></button></td></tr>)}</tbody></table></div></div>
 {selected&&<ActionModal title="Application actions" subtitle={`${selected.candidate} · ${selected.role}`} onClose={()=>setSelected(null)}><div className="fit-grid"><div><span>Current stage</span><b>{selected.stage}</b></div><div><span>Match score</span><b>{selected.match}%</b></div></div><div className="mt-3"><label className="form-label">Move stage</label><select className="form-select" value={selected.stage} onChange={e=>setStage(e.target.value)}>{stageOrder.map(s=><option key={s}>{s}</option>)}</select></div></ActionModal>}
 </>}
