import { useEffect, useMemo, useState } from 'react'
import { getInterviews, getApplications, createInterview } from '../services/api'
import ActionModal from '../components/ActionModal'
import { downloadCsv } from '../utils/exportCsv'

export default function Interviews(){
 const [items,setItems]=useState([]);const [applications,setApplications]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [showSchedule,setShowSchedule]=useState(false);const [showCalendar,setShowCalendar]=useState(false);const [showFeedback,setShowFeedback]=useState(false);const [form,setForm]=useState({application_id:'',interview_type:'Technical',scheduled_at:''});const [saving,setSaving]=useState(false)
 async function load(){setLoading(true);setError('');try{const [i,a]=await Promise.all([getInterviews(),getApplications()]);setItems(i.items||[]);setApplications(a.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const pending=items.filter(i=>i.status==='Scheduled').length, completed=items.filter(i=>i.status==='Completed').length; const scored=items.filter(i=>typeof i.score==='number'); const average=scored.length?Math.round(scored.reduce((n,i)=>n+i.score,0)/scored.length):0; const workload=useMemo(()=>items.reduce((m,i)=>(m[i.interviewer]=(m[i.interviewer]||0)+1,m),{}),[items])
 async function schedule(e){e.preventDefault();setSaving(true);try{await createInterview({...form});setShowSchedule(false);setForm({application_id:'',interview_type:'Technical',scheduled_at:''});await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <><div className="page-title-row"><div><div className="eyebrow">INTERVIEW OPERATIONS</div><h1>Interviews</h1><p>Coordinate interviews and keep feedback moving.</p></div><button className="btn btn-primary-custom" onClick={()=>setShowSchedule(true)}><i className="bi bi-calendar-plus me-2"/>Schedule interview</button></div>
 {error&&<div className="alert alert-warning">{error}</div>}
 <div className="kpi-grid compact-kpis"><div className="mini-stat"><span>Upcoming</span><strong>{pending}</strong><small>Live interview records</small></div><div className="mini-stat"><span>Completed</span><strong>{completed}</strong><small>Completed records</small></div><div className="mini-stat"><span>Feedback pending</span><strong>{items.filter(i=>i.status==='Completed'&&i.score==null).length}</strong><small>Needs attention</small></div><div className="mini-stat"><span>Avg. score</span><strong>{average}%</strong><small>Scored interviews</small></div></div>
 <div className="panel mt-4"><div className="panel-head"><div><h3>Interview schedule</h3><p>{loading?'Loading live interviews...':'Interview records from PostgreSQL.'}</p></div><div className="d-flex gap-2"><button className="btn btn-outline-soft" onClick={()=>setShowCalendar(true)}><i className="bi bi-calendar3 me-2"/>Calendar</button><button className="btn btn-outline-soft" onClick={()=>downloadCsv('hiresense-interviews.csv',items)}><i className="bi bi-download"/></button></div></div><div className="table-responsive"><table className="table align-middle candidate-table"><thead><tr><th>Candidate</th><th>Role</th><th>Date & time</th><th>Round</th><th>Interviewer</th><th>Status</th></tr></thead><tbody>{!loading&&items.map(i=><tr key={i.id}><td><div className="candidate-name"><div className="avatar-sm">{i.candidate.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><strong>{i.candidate}</strong></div></td><td>{i.role}</td><td>{i.date_label}</td><td>{i.round}</td><td>{i.interviewer}</td><td><span className={`status ${i.status==='Scheduled'?'shortlisted':'offer'}`}>{i.status}</span></td></tr>)}</tbody></table></div></div>
 <div className="row g-4 mt-1"><div className="col-lg-7"><div className="panel"><div className="panel-head"><div><h3>Interviewer workload</h3><p>Live distribution of interview records.</p></div></div>{Object.entries(workload).map(([name,count])=><div className="workload" key={name}><div><strong>{name}</strong><span>{count} interviews</span></div><div className="workload-bar"><span style={{width:`${Math.min(count/Math.max(pending,1)*100,100)}%`}}/></div></div>)}</div></div><div className="col-lg-5"><div className="panel"><div className="panel-head"><div><h3>Feedback health</h3><p>Interview scoring coverage.</p></div></div><div className="feedback-score">{scored.length?Math.round(scored.length/Math.max(items.length,1)*100):0}<span>%</span></div><p className="small-muted">of interview records currently have a score captured.</p><button className="text-btn mt-2" onClick={()=>setShowFeedback(true)}>Review feedback <i className="bi bi-arrow-right"/></button></div></div></div>
 {showSchedule&&<ActionModal title="Schedule interview" subtitle="Create a live interview record for an application." onClose={()=>setShowSchedule(false)} footer={<><button className="btn btn-outline-soft" onClick={()=>setShowSchedule(false)}>Cancel</button><button form="schedule-form" className="btn btn-primary-custom" disabled={saving}>{saving?'Scheduling…':'Schedule interview'}</button></>}><form id="schedule-form" onSubmit={schedule} className="vstack gap-3"><div><label className="form-label">Application</label><select required className="form-select" value={form.application_id} onChange={e=>setForm({...form,application_id:e.target.value})}><option value="">Select application</option>{applications.map(a=><option key={a.id} value={a.id}>{a.candidate} · {a.role}</option>)}</select></div><div><label className="form-label">Round</label><select className="form-select" value={form.interview_type} onChange={e=>setForm({...form,interview_type:e.target.value})}><option>Technical</option><option>Hiring Manager</option><option>HR</option></select></div><div><label className="form-label">Date & time</label><input required type="datetime-local" className="form-control" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></div></form></ActionModal>}
 {showCalendar&&<ActionModal title="Interview calendar" subtitle="Upcoming and scheduled interviews." onClose={()=>setShowCalendar(false)}><div className="vstack gap-2">{items.filter(i=>i.status==='Scheduled').map(i=><div className="mini-stat" key={i.id}><strong>{i.date_label}</strong><span>{i.candidate} · {i.role}</span><small>{i.round} · {i.interviewer}</small></div>)}{!items.some(i=>i.status==='Scheduled')&&<p className="small-muted">No upcoming interviews scheduled.</p>}</div></ActionModal>}
 {showFeedback&&<ActionModal title="Feedback review" subtitle="Identify interviews that still need scoring." onClose={()=>setShowFeedback(false)}><div className="vstack gap-2">{items.filter(i=>i.status==='Completed').map(i=><div className="mini-stat" key={i.id}><strong>{i.candidate}</strong><span>{i.role} · {i.round}</span><small>{i.score==null?'Feedback pending':`Score ${i.score}%`}</small></div>)}</div></ActionModal>}
 </>}
