import { useEffect, useMemo, useState } from 'react'
import { getInterviews } from '../services/api'

export default function Interviews(){
 const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{getInterviews().then(d=>setItems(d.items||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 const pending=items.filter(i=>i.status==='Scheduled').length
 const completed=items.filter(i=>i.status==='Completed').length
 const scored=items.filter(i=>typeof i.score==='number')
 const average=scored.length?Math.round(scored.reduce((n,i)=>n+i.score,0)/scored.length):0
 const workload=useMemo(()=>items.reduce((map,i)=>(map[i.interviewer]=(map[i.interviewer]||0)+1,map),{}),[items])
 return <><div className="page-title-row"><div><div className="eyebrow">INTERVIEW OPERATIONS</div><h1>Interviews</h1><p>Coordinate interviews and keep feedback moving.</p></div><button className="btn btn-primary-custom"><i className="bi bi-calendar-plus me-2"/>Schedule interview</button></div>
 {error&&<div className="alert alert-warning">Backend unavailable: {error}</div>}
 <div className="kpi-grid compact-kpis"><div className="mini-stat"><span>Upcoming</span><strong>{pending}</strong><small>Live interview records</small></div><div className="mini-stat"><span>Completed</span><strong>{completed}</strong><small>Completed records</small></div><div className="mini-stat"><span>Feedback pending</span><strong>{items.filter(i=>i.status==='Completed'&&i.score==null).length}</strong><small>Needs attention</small></div><div className="mini-stat"><span>Avg. score</span><strong>{average}%</strong><small>Scored interviews</small></div></div>
 <div className="panel mt-4"><div className="panel-head"><div><h3>Interview schedule</h3><p>{loading?'Loading live interviews...':'Interview records from PostgreSQL.'}</p></div><button className="btn btn-outline-soft"><i className="bi bi-calendar3 me-2"/>Calendar</button></div><div className="table-responsive"><table className="table align-middle candidate-table"><thead><tr><th>Candidate</th><th>Role</th><th>Date & time</th><th>Round</th><th>Interviewer</th><th>Status</th></tr></thead><tbody>{!loading&&items.map(i=><tr key={i.id}><td><div className="candidate-name"><div className="avatar-sm">{i.candidate.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><strong>{i.candidate}</strong></div></td><td>{i.role}</td><td>{i.date_label}</td><td>{i.round}</td><td>{i.interviewer}</td><td><span className={`status ${i.status==='Scheduled'?'shortlisted':'offer'}`}>{i.status}</span></td></tr>)}</tbody></table></div></div>
 <div className="row g-4 mt-1"><div className="col-lg-7"><div className="panel"><div className="panel-head"><div><h3>Interviewer workload</h3><p>Live distribution of interview records.</p></div></div>{Object.entries(workload).map(([name,count])=><div className="workload" key={name}><div><strong>{name}</strong><span>{count} interviews</span></div><div className="workload-bar"><span style={{width:`${Math.min(count/Math.max(pending,1)*100,100)}%`}}/></div></div>)}</div></div><div className="col-lg-5"><div className="panel"><div className="panel-head"><div><h3>Feedback health</h3><p>Interview scoring coverage.</p></div></div><div className="feedback-score">{scored.length?Math.round(scored.length/Math.max(items.length,1)*100):0}<span>%</span></div><p className="small-muted">of interview records currently have a score captured.</p><button className="text-btn mt-2">Review feedback <i className="bi bi-arrow-right"/></button></div></div></div></>}
