import { useEffect, useMemo, useState } from 'react'
import { getJobs, createJob } from '../services/api'
import ActionModal from '../components/ActionModal'
import { downloadCsv } from '../utils/exportCsv'

export default function Jobs({onNavigate}){
 const [jobs,setJobs]=useState([]); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [showCreate,setShowCreate]=useState(false); const [selected,setSelected]=useState(null); const [form,setForm]=useState({title:'',department:'Data',location:'Remote',openings:1}); const [saving,setSaving]=useState(false)
 async function load(){setLoading(true);setError('');try{const d=await getJobs({search:query,status:filter});setJobs(d.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[query,filter])
 const stats=useMemo(()=>({open:jobs.filter(j=>j.status==='Open').length,applicants:jobs.reduce((n,j)=>n+j.applicants,0),avg:jobs.length?Math.round(jobs.reduce((n,j)=>n+j.applicants,0)/jobs.length):0,critical:jobs.filter(j=>j.priority==='High').length}),[jobs])
 async function saveJob(e){e.preventDefault();setSaving(true);setError('');try{await createJob({...form,openings:Number(form.openings)});setShowCreate(false);setForm({title:'',department:'Data',location:'Remote',openings:1});await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <>
  <div className="page-title-row"><div><div className="eyebrow">WORKFORCE PLANNING</div><h1>Jobs</h1><p>Manage open roles and monitor hiring demand across teams.</p></div><button className="btn btn-primary-custom" onClick={()=>setShowCreate(true)}><i className="bi bi-plus-lg me-2"/>Create job</button></div>
  {error&&<div className="alert alert-warning">{error}</div>}
  <div className="kpi-grid compact-kpis"><div className="mini-stat"><span>Open roles</span><strong>{stats.open}</strong><small>From live database</small></div><div className="mini-stat"><span>Total applicants</span><strong>{stats.applicants.toLocaleString()}</strong><small>Across loaded roles</small></div><div className="mini-stat"><span>Avg. applicants / job</span><strong>{stats.avg}</strong><small>Current role average</small></div><div className="mini-stat"><span>Critical roles</span><strong>{stats.critical}</strong><small>Need attention</small></div></div>
  <div className="panel filters-panel mb-4"><div className="search-wrap"><i className="bi bi-search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search jobs, departments, or locations..."/></div><select className="form-select filter-select" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Open</option><option>Closed</option></select></div>
  <div className="job-grid">{loading?<div className="panel p-5 text-center">Loading jobs...</div>:jobs.map(j=><article className="job-card" key={j.id}><div className="job-top"><span className={`priority ${j.priority.toLowerCase()}`}>{j.priority} priority</span><span className={`status ${j.status.toLowerCase()}`}>{j.status}</span></div><div className="job-icon"><i className="bi bi-briefcase"/></div><h3>{j.title}</h3><p>{j.dept}</p><div className="job-meta"><span><i className="bi bi-geo-alt"/> {j.location}</span><span><i className="bi bi-clock"/> {j.type}</span></div><div className="skill-chips">{j.skills.map(s=><span key={s}>{s}</span>)}</div><div className="job-stats"><div><b>{j.applicants}</b><span>Applicants</span></div><div><b>{j.shortlisted}</b><span>Shortlisted</span></div><div><b>{j.days}d</b><span>Open time</span></div></div><button className="job-action" onClick={()=>setSelected(j)}>View pipeline <i className="bi bi-arrow-right"/></button></article>)}</div>
  {showCreate&&<ActionModal title="Create job" subtitle="Create a new opening in the live recruitment database." onClose={()=>setShowCreate(false)} footer={<><button className="btn btn-outline-soft" onClick={()=>setShowCreate(false)}>Cancel</button><button form="job-form" className="btn btn-primary-custom" disabled={saving}>{saving?'Creating…':'Create job'}</button></>}><form id="job-form" onSubmit={saveJob} className="vstack gap-3"><div><label className="form-label">Job title</label><input className="form-control" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="row g-3"><div className="col-md-6"><label className="form-label">Department</label><input className="form-control" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Location</label><input className="form-control" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div></div><div><label className="form-label">Openings</label><input type="number" min="1" className="form-control" value={form.openings} onChange={e=>setForm({...form,openings:e.target.value})}/></div></form></ActionModal>}
  {selected&&<ActionModal title={`${selected.title} pipeline`} subtitle={`${selected.applicants} applicants · ${selected.shortlisted} shortlisted`} onClose={()=>setSelected(null)} footer={<button className="btn btn-primary-custom" onClick={()=>{setSelected(null);onNavigate?.('Applications')}}>Open applications</button>}><div className="fit-grid"><div><span>Department</span><b>{selected.dept}</b></div><div><span>Location</span><b>{selected.location}</b></div><div><span>Openings</span><b>{selected.openings}</b></div><div><span>Status</span><b>{selected.status}</b></div></div><div className="ai-mini mt-3"><i className="bi bi-graph-up-arrow"/><p>This role currently has {selected.applicants} applicants and {selected.shortlisted} people at or beyond the shortlisted stage.</p></div></ActionModal>}
 </>
}
