import { useEffect, useMemo, useState } from 'react'
import { getJobs } from '../services/api'

export default function Jobs(){
 const [jobs,setJobs]=useState([]); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{setLoading(true);setError('');getJobs({search:query,status:filter}).then(d=>setJobs(d.items||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[query,filter])
 const stats=useMemo(()=>({open:jobs.filter(j=>j.status==='Open').length,applicants:jobs.reduce((n,j)=>n+j.applicants,0),avg:jobs.length?Math.round(jobs.reduce((n,j)=>n+j.applicants,0)/jobs.length):0,critical:jobs.filter(j=>j.priority==='High').length}),[jobs])
 return <>
  <div className="page-title-row"><div><div className="eyebrow">WORKFORCE PLANNING</div><h1>Jobs</h1><p>Manage open roles and monitor hiring demand across teams.</p></div><button className="btn btn-primary-custom"><i className="bi bi-plus-lg me-2"/>Create job</button></div>
  {error&&<div className="alert alert-warning">Backend unavailable: {error}</div>}
  <div className="kpi-grid compact-kpis"><div className="mini-stat"><span>Open roles</span><strong>{stats.open}</strong><small>From live database</small></div><div className="mini-stat"><span>Total applicants</span><strong>{stats.applicants.toLocaleString()}</strong><small>Across loaded roles</small></div><div className="mini-stat"><span>Avg. applicants / job</span><strong>{stats.avg}</strong><small>Current role average</small></div><div className="mini-stat"><span>Critical roles</span><strong>{stats.critical}</strong><small>Need attention</small></div></div>
  <div className="panel filters-panel mb-4"><div className="search-wrap"><i className="bi bi-search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search jobs, departments, or locations..."/></div><select className="form-select filter-select" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Open</option><option>Closed</option></select></div>
  <div className="job-grid">{loading?<div className="panel p-5 text-center">Loading jobs...</div>:jobs.map(j=><article className="job-card" key={j.id}><div className="job-top"><span className={`priority ${j.priority.toLowerCase()}`}>{j.priority} priority</span><span className={`status ${j.status.toLowerCase()}`}>{j.status}</span></div><div className="job-icon"><i className="bi bi-briefcase"/></div><h3>{j.title}</h3><p>{j.dept}</p><div className="job-meta"><span><i className="bi bi-geo-alt"/> {j.location}</span><span><i className="bi bi-clock"/> {j.type}</span></div><div className="skill-chips">{j.skills.map(s=><span key={s}>{s}</span>)}</div><div className="job-stats"><div><b>{j.applicants}</b><span>Applicants</span></div><div><b>{j.shortlisted}</b><span>Shortlisted</span></div><div><b>{j.days}d</b><span>Open time</span></div></div><button className="job-action">View pipeline <i className="bi bi-arrow-right"/></button></article>)}</div>
 </>
}
