import { useEffect, useState } from 'react'

export default function Settings({user}){
 const [notifications,setNotifications]=useState(()=>localStorage.getItem('hire_notifications')!=='off')
 const [compact,setCompact]=useState(()=>localStorage.getItem('hire_compact')==='on')
 useEffect(()=>{localStorage.setItem('hire_notifications',notifications?'on':'off')},[notifications])
 useEffect(()=>{localStorage.setItem('hire_compact',compact?'on':'off');document.body.classList.toggle('compact-ui',compact)},[compact])
 return <><div className="page-title-row"><div><div className="eyebrow">SYSTEM SETTINGS</div><h1>Settings</h1><p>Manage recruiter workspace preferences and account information.</p></div></div><div className="row g-4"><div className="col-lg-7"><div className="panel"><div className="panel-head"><div><h3>Workspace preferences</h3><p>These preferences are saved in this browser.</p></div></div><div className="settings-row"><div><strong>Email notifications</strong><p>Show recruitment reminders and activity alerts.</p></div><button className={`btn ${notifications?'btn-primary-custom':'btn-outline-soft'}`} onClick={()=>setNotifications(!notifications)}>{notifications?'Enabled':'Disabled'}</button></div><div className="settings-row"><div><strong>Compact interface</strong><p>Reduce spacing for a denser recruiter workspace.</p></div><button className={`btn ${compact?'btn-primary-custom':'btn-outline-soft'}`} onClick={()=>setCompact(!compact)}>{compact?'Enabled':'Disabled'}</button></div></div></div><div className="col-lg-5"><div className="panel"><div className="panel-head"><div><h3>Account</h3><p>Authenticated recruiter session.</p></div></div><div className="fit-grid"><div><span>Name</span><b>{user?.name||'Recruiter'}</b></div><div><span>Role</span><b>{user?.role||'Recruiter'}</b></div><div><span>Email</span><b>{user?.email||'—'}</b></div><div><span>Session</span><b>Protected</b></div></div></div><div className="panel mt-4"><div className="ai-mini"><i className="bi bi-shield-check"/><p>API keys stay server-side. Workspace preferences stored here never leave this browser.</p></div></div></div></div></>
}
